<?php


namespace frontend\models;


use yii\db\ActiveRecord;

class AddProductsForm extends ActiveRecord
{
    public static function tableName()
    {
        return 'products'; // TODO: Change the autogenerated stub
    }
    public function attributeLabels()
    {
        return [
            'name' => 'Имя',
            'description' => 'Описание',
            'price' => 'Цена, руб.',
            'categories_id' => 'Категория',
        ];
    }

    public function rules()
    {
        return [
            [['name', 'description', 'price'], 'required'],
            ['categories_id', 'trim'],
        ];
    }
}